video_new:
    path:   /new
    defaults: { _controller: "AppBundle:video:new"}
    methods:  POST
    
video_edit:
    path:   /edit/{id}
    defaults: { _controller: "AppBundle:video:edit", id:null }
    methods:  POST
    